apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: fake
    baseDeviceInfos: '{"Ascend910-0":{"IP":"10.10.113.21","SuperDeviceID":4290772992},"Ascend910-1":{"IP":"10.10.113.22","SuperDeviceID":4291035137},"Ascend910-2":{"IP":"10.10.113.23","SuperDeviceID":4291297282},"Ascend910-3":{"IP":"10.10.113.24","SuperDeviceID":4291559427},"Ascend910-4":{"IP":"10.10.113.25","SuperDeviceID":4291821572},"Ascend910-5":{"IP":"10.10.113.26","SuperDeviceID":4292083717},"Ascend910-6":{"IP":"10.10.113.27","SuperDeviceID":4292345862},"Ascend910-7":{"IP":"10.10.113.28","SuperDeviceID":4292608007}}'
  labels:
    beta.kubernetes.io/arch: arm64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: arm64
    kubernetes.io/hostname: kwok-node-0
    kubernetes.io/os: linux
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
    accelerator: huawei-Ascend910
    host-arch: huawei-x86
    type: kwok
  name: kwok-node-0
spec:
  taints: # Avoid scheduling actual running pods to fake Node
  - effect: NoSchedule
    key: kwok.x-k8s.io/node
    value: fake
status:
  allocatable:
    cpu: 96
    memory: 720Gi
    huawei.com/Ascend910: 8
    pods: 110
  capacity:
    cpu: 96
    memory: 720Gi
    huawei.com/Ascend910: 8
    pods: 110
  nodeInfo:
    architecture: arm64
    bootID: ""
    containerRuntimeVersion: ""
    kernelVersion: ""
    kubeProxyVersion: fake
    kubeletVersion: fake
    machineID: ""
    operatingSystem: linux
    osImage: ""
    systemUUID: ""
  phase: Running
