apiVersion: mindxdl.gitee.com/v1
kind: AscendJob
metadata:
  name: acjob-test-time-100-1
  namespace: default
  labels:
    framework: pytorch
    ring-controller.atlas: ascend-910b
    fault-scheduling: "force"
spec:
  schedulerName: volcano    # work when enableGangScheduling is true
  runPolicy:
    schedulingPolicy:       # work when enableGangScheduling is true
      minAvailable: 1
      queue: default
  successPolicy: AllWorkers
  replicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          labels:
            ring-controller.atlas: ascend-910b
        spec:
          #terminationGracePeriodSeconds: 180
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: job-name
                        operator: In
                        values:
                          - acjob-test-time-100-1
                  topologyKey: kubernetes.io/hostname
          nodeSelector:
            host-arch: huawei-x86
            #accelerator-type: module-910b-8
          hostNetwork: true
          hostPID: true
          containers:
          - name: ascend # do not modify
            image: conda:cann     # training framework image， which can be modified
            imagePullPolicy: IfNotPresent
            command:                          # training command, which can be modified
              - /bin/bash
              - -c
            args: ["sleep 10000"]
            ports:                          # default value containerPort: 2222 name: ascendjob-port if not set
              - containerPort: 2222         # determined by user
                name: ascendjob-port        # do not modify
              - containerPort: 8000
                name: ttp-port
            resources:
              limits:
                 huawei.com/Ascend910: 1
              requests:
                 huawei.com/Ascend910: 1
